In [15]:
import numpy as np

In [16]:
import warnings
warnings.filterwarnings('ignore')

In [27]:
cab_data =np.genfromtxt(r"C:\Users\rakes\Downloads\nyc_taxis.csv",delimiter = ',',skip_header = True, dtype = int)
cab_data.shape
cab_data.ndim
cab_data

array([[2016,    1,    1, ...,   11,   69,    1],
       [2016,    1,    1, ...,    8,   54,    1],
       [2016,    1,    1, ...,    0,   37,    2],
       ...,
       [2016,    6,   30, ...,    5,   63,    1],
       [2016,    6,   30, ...,    8,   44,    1],
       [2016,    6,   30, ...,    0,   54,    2]])

In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\rakes\Downloads\nyc_taxis.csv")
df

pickup_year  pickup_month  pickup_day  pickup_dayofweek  pickup_time  \
0             2016             1           1                 5            0   
1             2016             1           1                 5            0   
2             2016             1           1                 5            0   
3             2016             1           1                 5            0   
4             2016             1           1                 5            0   
...            ...           ...         ...               ...          ...   
89555         2016             6          30                 4            5   
89556         2016             6          30                 4            5   
89557         2016             6          30                 4            5   
89558         2016             6          30                 4            5   
89559         2016             6          30                 4            5   

       pickup_location_code  dropoff_location_code  trip_distance  \
0                         2                      4          21.00   
1                         2                      1          16.29   
2                         2                      6          12.70   
3                         2                      6           8.70   
4                         2                      6           5.56   
...                     ...                    ...            ...   
89555                     3                      4           9.50   
89556                     2                      4          19.80   
89557                     2                      4          17.48   
89558                     2                      6          12.76   
89559                     2                      0          17.54   

       trip_length  fare_amount  fees_amount  tolls_amount  tip_amount  \
0             2037         52.0          0.8          5.54       11.65   
1             1520         45.0          1.3          0.00        8.00   
2             1462         36.5          1.3          0.00        0.00   
3             1210         26.0          1.3          0.00        5.46   
4              759         17.5          1.3          0.00        0.00   
...            ...          ...          ...           ...         ...   
89555         1989         31.0          1.3          5.54        3.00   
89556         2368         52.0          0.8          5.54        0.00   
89557         2822         52.0          0.8          5.54        5.00   
89558         1083         34.5          1.3          0.00        8.95   
89559         1711         48.0          1.3          5.54        0.00   

       total_amount  payment_type  
0             69.99             1  
1             54.30             1  
2             37.80             2  
3             32.76             1  
4             18.80             2  
...             ...           ...  
89555         40.84             1  
89556         58.34             1  
89557         63.34             1  
89558         44.75             1  
89559         54.84             2  

[89560 rows x 15 columns]

In [117]:
df.columns
# df.head(10)
df.info()
df.isnull().sum()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89560 entries, 0 to 89559
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   pickup_year            89560 non-null  int64  
 1   pickup_month           89560 non-null  int64  
 2   pickup_day             89560 non-null  int64  
 3   pickup_dayofweek       89560 non-null  int64  
 4   pickup_time            89560 non-null  int64  
 5   pickup_location_code   89560 non-null  int64  
 6   dropoff_location_code  89560 non-null  int64  
 7   trip_distance          89560 non-null  float64
 8   trip_length            89560 non-null  int64  
 9   fare_amount            89560 non-null  float64
 10  fees_amount            89560 non-null  float64
 11  tolls_amount           89560 non-null  float64
 12  tip_amount             89560 non-null  float64
 13  total_amount           89560 non-null  float64
 14  payment_type           89560 non-null  int64  
dtypes:

pickup_year              0
pickup_month             0
pickup_day               0
pickup_dayofweek         0
pickup_time              0
pickup_location_code     0
dropoff_location_code    0
trip_distance            0
trip_length              0
fare_amount              0
fees_amount              0
tolls_amount             0
tip_amount               0
total_amount             0
payment_type             0
dtype: int64

## 1.Mean Speed of all the rides
    speed = distance/time

In [98]:
speed = cab_data[:,7]/ (cab_data[:,8]/3600)  ## We have length, we assume that length in sec, so we need to convert the length into time(in seconds).
speed

array([37.11340206, 37.89473684, 29.54856361, ..., 21.68674699,
       39.88919668, 35.7685564 ])

In [99]:
## Now we need to calculate the mean of the speed.
mean_speed = speed.mean()
mean_speed    #Final output of the mean speed.

30.664805016170458

In [95]:
# ANSWER
# Mean speed of all Rides is '32.24'.

## 2. Number Of Rides Taken in February

In [93]:

rides_feb = cab_data[cab_data[ :,1] == 2, 1]

rides_feb.size


13333

In [94]:
# ANSWER
# Nuber of rides taken in february is '13333'.

## 3. Number of rides tip more then $50?

In [111]:
tip = cab_data[:,-3]
tip

array([11,  8,  0, ...,  5,  8,  0])

In [72]:
tip_count = []
for i in tip:
    if i > 50:
     tip_count.append(i)

In [74]:
tip50 = np.array(tip_count).size
tip50

16

In [76]:
# METHOD - 2
cab_data[cab_data[:,-3]>50 , -3].size

16

In [ ]:
# ANSWER:-
# Number of rides with tip more then $50 is '16'.

## 4. Number of rides where drop was JFK Airport?


In [82]:
# Method-1
cab_data[cab_data[:,6]==2, 6].size

11832

In [84]:
# METHOD-2
drop_loc = cab_data[:,6]
drop_loc

array([4, 1, 6, ..., 4, 6, 0])

In [85]:
JFK_count = []
for i in drop_loc:
    if i == 2:
        JFK_count.append(i)
        

In [89]:
JFK_count
np.array(JFK_count).size

11832

In [90]:
# ANSWER:-
# Number of drops at JFK Airport is '11832'.

## 5. Minimum ,maximum and average far_amount of a ride?

In [103]:
fare_amount = cab_data[:,-6]
fare_amount

array([52, 45, 36, ..., 52, 34, 48])

In [104]:
np.min(fare_amount)

-52

In [105]:
np.max(fare_amount)

400

In [112]:
## Total amount after adding all the charges and tips?
total_amount = cab_data[:,-2]
total_amount

array([69, 54, 37, ..., 63, 44, 54])

In [132]:
np.min(total_amount) ##MIN OF FARE AMOUNT

-58

In [114]:
np.max(total_amount  ##MAX OF FARE AMOUNT

834

In [131]:
np.mean(total_amount)  ##AVERAGE OF FARE AMOUNT

48.45901071907102

## 6. Number of trips per month

In [119]:
trips = cab_data[:,1]

In [120]:
np.unique(trips)

array([1, 2, 3, 4, 5, 6])

In [121]:
trips

array([1, 1, 1, ..., 6, 6, 6])

In [125]:
month,rides = np.unique(trips,return_counts = True)
month
rides

array([13481, 13333, 15547, 14810, 16650, 15739], dtype=int64)

In [128]:
trips_per_month = dict(zip(month,rides))
trips_per_month


{1: 13481, 2: 13333, 3: 15547, 4: 14810, 5: 16650, 6: 15739}

In [130]:
# ANSWER
# NUMBER OF TRIPS PER MONTH IS:--- {1: 13481, 2: 13333, 3: 15547, 4: 14810, 5: 16650, 6: 15739}

## 7. How Locations that cab went on overall NYC?

In [134]:
pickup_location = cab_data[:,5]
pickup_location

array([2, 2, 2, ..., 2, 2, 2])

In [135]:
drop_location = cab_data[:,6]
drop_location

array([4, 1, 6, ..., 4, 6, 0])

In [141]:
locations = np.unique(pickup_location + drop_location)

In [142]:
locations.size

9

In [143]:
# ANSWER
# TOTAL LOCATIONS THAT THE CAB WENT IS '9'.

## 8. Fare amount Percentage
    %fare amount = fare_amount/total_amount

In [146]:
fare_amount = cab_data[:,9]
fare_amount

array([52, 45, 36, ..., 52, 34, 48])

In [147]:
total_amount = cab_data[:,13]
total_amount

array([69, 54, 37, ..., 63, 44, 54])

In [154]:
fare_amount_percentage = fare_amount/total_amount*100
fare_amount_percentage



array([1.09220752, 1.54320988, 2.62965668, ..., 1.31015369, 1.75619835,
       1.64609053])

## 9. Types of payments done by the customer

In [160]:
payments = cab_data[:,-1]
payments

array([1, 1, 2, ..., 1, 1, 2])

In [164]:
payment_types,count = np.unique(payments, return_counts = True )
payment_types
count

array([64356, 24520,   560,   124], dtype=int64)

In [165]:
payment_types.size

4

In [ ]:
# ANSWER
# '4' Types of payments are used by the customer

## 10. MIn and Max Distance travelled by the cab

In [168]:
trip_distance = cab_data[:,7]
trip_distance

array([21, 16, 12, ..., 17, 12, 17])

In [169]:
np.min(trip_distance)

0

In [170]:
np.max(trip_distance)

182

In [171]:
np.mean(trip_distance)

12.197096918267084