In [15]:
import numpy as np

In [16]:
import warnings
warnings.filterwarnings('ignore')

In [27]:
cab_data =np.genfromtxt(r"C:\Users\rakes\Downloads\nyc_taxis.csv",delimiter = ',',skip_header = True, dtype = int)
cab_data.shape
cab_data.ndim
cab_data

array([[2016,    1,    1, ...,   11,   69,    1],
       [2016,    1,    1, ...,    8,   54,    1],
       [2016,    1,    1, ...,    0,   37,    2],
       ...,
       [2016,    6,   30, ...,    5,   63,    1],
       [2016,    6,   30, ...,    8,   44,    1],
       [2016,    6,   30, ...,    0,   54,    2]])

In [3]:
import pandas as pd
df = pd.read_csv(r"C:\Users\rakes\Downloads\nyc_taxis.csv")
df

pickup_year  pickup_month  pickup_day  pickup_dayofweek  pickup_time  \
0             2016             1           1                 5            0   
1             2016             1           1                 5            0   
2             2016             1           1                 5            0   
3             2016             1           1                 5            0   
4             2016             1           1                 5            0   
...            ...           ...         ...               ...          ...   
89555         2016             6          30                 4            5   
89556         2016             6          30                 4            5   
89557         2016             6          30                 4            5   
89558         2016             6          30                 4            5   
89559         2016             6          30                 4            5   

       pickup_location_code  dropoff_location_code  trip_distance  \
0                         2                      4          21.00   
1                         2                      1          16.29   
2                         2                      6          12.70   
3                         2                      6           8.70   
4                         2                      6           5.56   
...                     ...                    ...            ...   
89555                     3                      4           9.50   
89556                     2                      4          19.80   
89557                     2                      4          17.48   
89558                     2                      6          12.76   
89559                     2                      0          17.54   

       trip_length  fare_amount  fees_amount  tolls_amount  tip_amount  \
0             2037         52.0          0.8          5.54       11.65   
1             1520         45.0          1.3          0.00        8.00   
2             1462         36.5          1.3          0.00        0.00   
3             1210         26.0          1.3          0.00        5.46   
4              759         17.5          1.3          0.00        0.00   
...            ...          ...          ...           ...         ...   
89555         1989         31.0          1.3          5.54        3.00   
89556         2368         52.0          0.8          5.54        0.00   
89557         2822         52.0          0.8          5.54        5.00   
89558         1083         34.5          1.3          0.00        8.95   
89559         1711         48.0          1.3          5.54        0.00   

       total_amount  payment_type  
0             69.99             1  
1             54.30             1  
2             37.80             2  
3             32.76             1  
4             18.80             2  
...             ...           ...  
89555         40.84             1  
89556         58.34             1  
89557         63.34             1  
89558         44.75             1  
89559         54.84             2  

[89560 rows x 15 columns]

In [78]:
df.columns
df.head(10)
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89560 entries, 0 to 89559
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   pickup_year            89560 non-null  int64  
 1   pickup_month           89560 non-null  int64  
 2   pickup_day             89560 non-null  int64  
 3   pickup_dayofweek       89560 non-null  int64  
 4   pickup_time            89560 non-null  int64  
 5   pickup_location_code   89560 non-null  int64  
 6   dropoff_location_code  89560 non-null  int64  
 7   trip_distance          89560 non-null  float64
 8   trip_length            89560 non-null  int64  
 9   fare_amount            89560 non-null  float64
 10  fees_amount            89560 non-null  float64
 11  tolls_amount           89560 non-null  float64
 12  tip_amount             89560 non-null  float64
 13  total_amount           89560 non-null  float64
 14  payment_type           89560 non-null  int64  
dtypes:

## 1.Mean Speed of all the rides
    speed = distance/time

In [19]:
speed = cab_data[:,7]/ (cab_data[:,8]/3600)  ## We have length, we assume that length in sec, so we need to convert the length into time(in seconds).
speed

array([37.11340206, 38.58157895, 31.27222982, ..., 22.29907867,
       42.41551247, 36.90473407])

In [21]:
## Now we need to calculate the mean of the speed.
mean_speed = speed.mean()
mean_speed    #Final output of the mean speed.

32.24258580925573

In [ ]:
# ANSWER
Me

## 2. Number Of Rides Taken in February

In [93]:

rides_feb = cab_data[cab_data[ :,1] == 2, 1]

rides_feb.size


13333

In [94]:
# ANSWER
# Nuber of rides taken in february is '13333'.

## 3. Number of rides tip more then $50?

In [65]:
tip = cab_data[:,-3]
tip

array([11,  8,  0, ...,  5,  8,  0])

In [72]:
tip_count = []
for i in tip:
    if i > 50:
     tip_count.append(i)

In [74]:
tip50 = np.array(tip_count).size
tip50

16

In [76]:
# METHOD - 2
cab_data[cab_data[:,-3]>50 , -3].size

16

In [ ]:
# ANSWER:-
# Number of rides with tip more then $50 is '16'.

## 4. Number of rides where drop was JFK Airport?


In [82]:
# Method-1
cab_data[cab_data[:,6]==2, 6].size

11832

In [84]:
# METHOD-2
drop_loc = cab_data[:,6]
drop_loc

array([4, 1, 6, ..., 4, 6, 0])

In [85]:
JFK_count = []
for i in drop_loc:
    if i == 2:
        JFK_count.append(i)
        

In [89]:
JFK_count
np.array(JFK_count).size

11832

In [90]:
# ANSWER:-
# Number of drops at JFK Airport is '11832'.